SAMPLES_PER_SECOND = 125
WINDOW_SIZE_IN_S = 3
FLOATS_PER_QUATERNION = 4
SAMPLES_PER_WINDOW = SAMPLES_PER_SECOND*WINDOW_SIZE_IN_S
QUATERNIONS_PER_WINDOW = SAMPLES_PER_SECOND*FLOATS_PER_QUATERNION*WINDOW_SIZE_IN_S
