SAMPLES_PER_SECOND = 125
WINDOW_SIZE_IN_S = 3
QUATERNIONS_PER_SAMPLE = 4
SAMPLES_PER_WINDOW = SAMPLES_PER_SECOND*WINDOW_SIZE_IN_S
QUATERNIONS_PER_WINDOW = SAMPLES_PER_SECOND*QUATERNIONS_PER_SAMPLE*WINDOW_SIZE_IN_S
